// src/app/privacypolicy/page.tsx
export default function PrivacyPolicy() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <h1 className="text-3xl font-bold mb-6">Kebijakan Privasi</h1>
      <p className="text-gray-600 mb-4">Terakhir diperbarui: [Tanggal]</p>
      
      <div className="prose max-w-none">
        <p>
          Kami, [Nama Perusahaan/Organisasi], menghormati privasi Anda dan berkomitmen untuk melindungi data pribadi Anda sesuai dengan ketentuan hukum yang berlaku, termasuk Undang-Undang Perlindungan Data Pribadi (UU PDP) di Indonesia. Kebijakan Privasi ini menjelaskan bagaimana kami mengumpulkan, menggunakan, dan melindungi data Anda ketika Anda menggunakan layanan kami.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-4">1. Informasi yang Dikumpulkan</h2>
        <p>Kami mengumpulkan data pribadi Anda untuk mendukung layanan yang kami tawarkan. Data yang dikumpulkan meliputi:</p>
        <ul className="list-disc pl-6">
          <li>Nama lengkap</li>
          <li>Alamat email</li>
          <li>Nomor telepon</li>
          <li>Gender</li>
          <li>Data aktivitas pengguna (soal yang dikerjakan, skor tes, riwayat pengerjaan soal)</li>
          <li>Asal universitas</li>
          <li>Status pendidikan (misalnya: mahasiswa aktif, lulus, atau lainnya)</li>
          <li>Angkatan masuk</li>
        </ul>

        {/* Lanjutkan dengan sections lainnya */}
        
        <h2 className="text-xl font-semibold mt-6 mb-4">7. Hubungi Kami</h2>
        <p>
          Jika Anda memiliki pertanyaan mengenai Kebijakan Privasi ini, Anda dapat menghubungi kami melalui email di: [Email Kontak].
        </p>
      </div>
    </div>
  );
}

// src/pages/PrivacyPolicy.vue
<template>
  <div class="container mx-auto px-4 py-8 max-w-4xl">
    <br><br>
    <h1 class="text-3xl font-bold mb-6"><center>Kebijakan Privasi</center></h1>  <br>
    <p class="text-gray-600 mb-4">Terakhir diperbarui: 25 Januari 2025</p>

    <div class="prose max-w-none space-y-6">
      <p>
        Kami, Berkompeten.id, berkomitmen untuk melindungi privasi dan data pribadi Anda. Kebijakan Privasi ini dibuat sebagai bentuk kepatuhan kami terhadap hukum dan regulasi yang berlaku, termasuk tetapi tidak terbatas pada Undang-Undang Perlindungan Data Pribadi (UU PDP) di Indonesia, Peraturan Pemerintah No. 71 Tahun 2019 tentang Penyelenggaraan Sistem dan Transaksi Elektronik (PP PSTE), serta standar perlindungan data pribadi lainnya yang relevan.
      </p>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">1. Lingkup Kebijakan Privasi</h2>
        <p>
          Kebijakan Privasi ini berlaku untuk semua individu yang mengakses dan/atau menggunakan aplikasi dan layanan kami, baik melalui platform berbasis web maupun aplikasi seluler. Dengan menggunakan layanan kami, Anda dianggap telah membaca, memahami, dan menyetujui Kebijakan Privasi ini, termasuk pengumpulan, penggunaan, dan pengolahan data pribadi Anda sesuai dengan ketentuan di dalamnya.
        </p>
      </div>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">2. Informasi yang Dikumpulkan</h2>
        <p>Kami mengumpulkan berbagai jenis data pribadi, termasuk:</p>
        <ul class="list-disc pl-6 mt-2">
          <li>Nama lengkap</li>
          <li>Alamat email</li>
          <li>Nomor telepon</li>
          <li>Gender</li>
          <li>Data aktivitas pengguna (soal yang dikerjakan, skor tes, riwayat pengerjaan soal)</li>
          <li>Asal universitas</li>
          <li>Status pendidikan (misalnya: mahasiswa aktif, lulusan, atau lainnya)</li>
          <li>Angkatan masuk</li>
        </ul>
        <p>
          Kami memastikan bahwa pengumpulan data ini dilakukan secara sah, adil, dan transparan, sesuai dengan prinsip-prinsip perlindungan data pribadi.
        </p>
      </div>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">3. Penggunaan Data Pribadi</h2>
        <p>Data pribadi Anda digunakan untuk tujuan berikut:</p>
        <ul class="list-disc pl-6 mt-2">
          <li>Memberikan layanan yang dipersonalisasi, termasuk rekomendasi belajar berbasis analitik</li>
          <li>Melakukan analisis dan evaluasi untuk meningkatkan kualitas dan efektivitas layanan kami</li>
          <li>Mendukung institusi pendidikan dalam memahami kebutuhan pembelajaran penggunanya (jika relevan)</li>
          <li>Memenuhi kewajiban hukum dan regulasi yang berlaku</li>
        </ul>
      </div>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">4. Penyimpanan dan Keamanan Data</h2>
        <p>
          Data pribadi Anda akan disimpan selama layanan ini aktif dan/atau selama diperlukan untuk memenuhi tujuan pengumpulan data tersebut. Kami menerapkan langkah-langkah teknis dan organisasi yang memadai guna memastikan data Anda tetap aman dari akses yang tidak sah, kerusakan, kehilangan, atau penyalahgunaan.
        </p>
      </div>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">5. Hak Pemilik Data Pribadi</h2>
        <p>Anda memiliki hak-hak berikut terkait data pribadi Anda:</p>
        <ul class="list-disc pl-6 mt-2">
          <li>
            <strong>Hak untuk Mengakses Data:</strong> Anda berhak meminta informasi terkait data pribadi Anda yang kami simpan.
          </li>
          <li>
            <strong>Hak untuk Mengoreksi Data:</strong> Anda berhak meminta perbaikan atas data yang tidak akurat, tidak lengkap, atau tidak relevan.
          </li>
          <li>
            <strong>Hak untuk Menghapus Data:</strong> Anda dapat meminta penghapusan data tertentu sesuai dengan ketentuan yang berlaku.
          </li>
          <li>
            <strong>Hak untuk Keberatan:</strong> Anda dapat menolak pemrosesan data pribadi Anda dalam keadaan tertentu.
          </li>
        </ul>
      </div>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">6. Pengungkapan Data Pribadi</h2>
        <p>Data pribadi Anda tidak akan diungkapkan kepada pihak ketiga kecuali dalam situasi berikut:</p>
        <ul class="list-disc pl-6 mt-2">
          <li>Jika diwajibkan oleh hukum, perintah pengadilan, atau permintaan resmi dari otoritas pemerintah yang berwenang</li>
          <li>Jika diperlukan oleh institusi pendidikan terkait untuk kepentingan pendidikan</li>
          <li>Jika Anda memberikan persetujuan eksplisit untuk pengungkapan tersebut</li>
        </ul>
      </div>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">7. Mekanisme Pengaduan</h2>
        <p>
          Kami menyediakan mekanisme pengaduan bagi pengguna yang merasa haknya terkait data pribadi telah dilanggar. Anda dapat mengajukan keluhan secara tertulis melalui email kami di 
          <a href="mailto:support@berkompeten.id" class="text-primary hover:underline">support@berkompeten.id</a>, dan kami akan merespons pengaduan Anda sesuai dengan waktu yang ditentukan dalam regulasi.
        </p>
      </div>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">8. Perubahan Kebijakan Privasi</h2>
        <p>
          Kami berhak mengubah Kebijakan Privasi ini dari waktu ke waktu untuk menyesuaikan dengan perkembangan hukum, teknologi, atau operasional layanan. Setiap perubahan yang signifikan akan diberitahukan kepada Anda melalui pemberitahuan resmi di aplikasi atau email.
        </p>
      </div>

      <div>
        <h2 class="text-xl font-semibold mt-6 mb-4">9. Kontak</h2>
        <p>
          Untuk informasi lebih lanjut terkait Kebijakan Privasi ini, silakan hubungi kami melalui email di 
          <a href="mailto:support@berkompeten.id" class="text-primary hover:underline">support@berkompeten.id</a>.
        </p>
      </div>
    </div>
  </div>
</template>
